### ISSUE TITLE
Failed at the allyoop@1.0.0 start script 'node_modules/react-native/packager/packager.sh'

### ISSUE THREAD

**Issue by xiongwuzhen** [wwayne/react-native-nba-app#10]
When launching "nam start", got the following error:

 ERROR  watchman--no-pretty get-sockname returned with exit code 1 2016-01-09T19:02:38,106: [cli] failed to identify PDU: fill_buffer: EOF
2016-01-09T19:02:38,107: [cli] unable to talk to your watchman on /usr/local/Cellar/watchman/4.1.0/var/run/watchman/xiong-state/sock! (Undefined error: 0)

Error: watchman--no-pretty get-sockname returned with exit code 1 2016-01-09T19:02:38,106: [cli] failed to identify PDU: fill_buffer: EOF
2016-01-09T19:02:38,107: [cli] unable to talk to your watchman on /usr/local/Cellar/watchman/4.1.0/var/run/watchman/xiong-state/sock! (Undefined error: 0)

```
at ChildProcess.<anonymous> (/Users/xiong/Documents/Application/react-native-nba/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:196:18)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Socket.<anonymous> (internal/child_process.js:319:11)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Pipe._onclose (net.js:469:12)
```

Failed at the allyoop@1.0.0 start script 'node_modules/react-native/packager/packager.sh'.

**Comment by wwayne** [comment]
@xiongwuzhen it works?

**Comment by xiongwuzhen** [comment]
Works fine. Thanks!
